### PR TITLE
Change stateManager.trie to stateManager._trie in GeneralStateTestsRunner

### LINKED ISSUE #390: Test fails if json trace is enabled
While trying to debug some tests for constantinople I run into the issue that some tests started failing when I enabled `--jsontrace`. 

Without `--jsontrace`:
`node ./tests/tester -s --fork='Constantinople' --test='extCodeHashDynamicArgument' --data=0 --gas=0 --value=0`
```
TAP version 13
# GeneralStateTests
# file: extCodeHashDynamicArgument test: extCodeHashDynamicArgument
ok 1 the state roots should match

1..1
# tests 1
# pass  1

# ok
```

with `--jsontrace`

`node ./tests/tester -s --fork='Constantinople' --test='extCodeHashDynamicArgument' --data=0 --gas=0 --value=0 --jsontrace`
```
TAP version 13
# GeneralStateTests
# file: extCodeHashDynamicArgument test: extCodeHashDynamicArgument
# {"pc":0,"op":96,"gas":"0x5c7b8","gasCost":"0x3","stack":[],"depth":0,"opName":"PUSH1"}
# {"pc":2,"op":53,"gas":"0x5c7b5","gasCost":"0x3","stack":["0x0"],"depth":0,"opName":"CALLDATALOAD"}
# {"pc":3,"op":63,"gas":"0x5c7b2","gasCost":"0x190","stack":["0x1"],"depth":0,"opName":"EXTCODEHASH"}
# {"pc":4,"op":96,"gas":"0x5c622","gasCost":"0x3","stack":["0x0"],"depth":0,"opName":"PUSH1"}
# {"pc":6,"op":85,"gas":"0x5c61f","gasCost":"0x0","stack":["0x0","0x0"],"depth":0,"opName":"SSTORE"}
# {"pc":7,"op":96,"gas":"0x5b297","gasCost":"0x3","stack":[],"depth":0,"opName":"PUSH1"}
# {"pc":9,"op":53,"gas":"0x5b294","gasCost":"0x3","stack":["0x0"],"depth":0,"opName":"CALLDATALOAD"}
# {"pc":10,"op":59,"gas":"0x5b291","gasCost":"0x2bc","stack":["0x1"],"depth":0,"opName":"EXTCODESIZE"}
# {"pc":11,"op":96,"gas":"0x5afd5","gasCost":"0x3","stack":["0x0"],"depth":0,"opName":"PUSH1"}
# {"pc":13,"op":85,"gas":"0x5afd2","gasCost":"0x0","stack":["0x0","0x1"],"depth":0,"opName":"SSTORE"}
not ok 1 the state roots should match
  ---
    operator: equal
    expected: |-
      '2ceab025ea1bcf156d3b82dcd37082bbd7550c50933057550a55a7dce4c06df0'
    actual: |-
      'dfbd02fee291d961905b27a5b42838a7c946fb89514534217e6bb3344d2dad71'
    at: replenish (/Users/rimeissner/gnosis/ethereumjs-vm/node_modules/async/dist/async.js:1011:17)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

This was done on the `eip-1052` branch (commit d661bded207aad5fb4385455ca978fd590f9a3de)

### PR DESCRIPTION
**Pull request by chikeichan**
Fix #390 

`stateManager.trie` should be `stateManager._trie` instead. I have also included a change to surface error message in test, as the testrunner was swallowing the error message, making it difficult to debug failing test.

### CODE REVIEW

File: tests/BlockchainTestsRunner.js [hunk 1]
```diff
@@ -91,6 +91,9 @@ module.exports = function runBlockchainTest (options, testData, t, cb) {
             cb(err)
           })
         } catch (err) {
+          if (err) {
+            console.log(err)
```
Comment (s1na) [inline tests/BlockchainTestsRunner.js]: Did you encounter errors here when testing? In that case, maybe explicitly failing with `t.fail(err)` would help find the errors.

File: tests/GeneralStateTestsRunner.js [hunk 2]
```diff
@@ -100,6 +100,9 @@ function runTestCase (options, testData, t, cb) {
           tx: tx,
           block: block
         }, function (err, r) {
+          if (err) {
+            console.log(err)
```
Comment (s1na) [inline tests/GeneralStateTestsRunner.js]: Same question as above

File: tests/BlockchainTestsRunner.js (hunk 1 above)
Comment (s1na) [reply tests/BlockchainTestsRunner.js]: Update: using `t.fail` will cause some invalid test cases to fail. We can just remove the `console.log` here.

Comment (chikeichan) [reply tests/BlockchainTestsRunner.js]: Good call! I updated the PR.

File: tests/GeneralStateTestsRunner.js (hunk 2 above)
Comment (chikeichan) [reply tests/GeneralStateTestsRunner.js]: updated

File: tests/BlockchainTestsRunner.js (hunk 1 above)
Comment (s1na) [reply tests/BlockchainTestsRunner.js]: Ah you changed it to `t.fail` :) sorry, my first comment was mistaken, I think we can ignore the error here, no need for any handling.

Comment (chikeichan) [reply tests/BlockchainTestsRunner.js]: I kinda like having the test fail here when it has err, otherwise it fails silently and make it a tad bit more difficult to debug. What do you think @s1na ?

File: tests/GeneralStateTestsRunner.js (hunk 2 above)
Comment (s1na) [reply tests/GeneralStateTestsRunner.js]: I definitely agree with you that its better to have tests fail explicitly. In this case however, tests are correct: they are testing that the VM functions correctly when input is invalid.

E.g. current state root is `0xdeadbeef`, when the VM is given an invalid tx (sender doesn't have enough gas), `runTx` throws an error. The tests later check that the state root shouldn't have changed for an invalid tx.

File: tests/BlockchainTestsRunner.js (hunk 1 above)
Comment (s1na) [reply tests/BlockchainTestsRunner.js]: Sorry, my comment was meant for the other one (GeneralStateTestsRunner), see below.

File: tests/GeneralStateTestsRunner.js (hunk 2 above)
Comment (chikeichan) [reply tests/GeneralStateTestsRunner.js]: make sense - updated!

File: tests/BlockchainTestsRunner.js (hunk 1 above)
Comment (chikeichan) [reply tests/BlockchainTestsRunner.js]: updated below

**Comment by s1na** [comment]
Thanks again for the PR and sorry for the nitpicks :)
