### PR TITLE
Fix Constantinople tests 

### LINKED ISSUE #928: Failing nightly build
The nightly build failures are due to massive Constantinople test failures for both State and Blockchain.

The current CI structure does not make easy to inspect specific errors, as they are under a single command (`npm run test:state:allForks`), so I had to run each test suite to investigate it:

image

### PR DESCRIPTION
**Pull request by evertonfraga**
Thanks for the contribution, @jochem-brouwer!

Closes #928 and fixes nightly builds.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Can we run the Constantinople tests in this PR just to (double) make sure that my claim it is fixed is actually true? 😄

**Comment by evertonfraga** [comment]
@jochem-brouwer sure! doing it now

**Comment by jochem-brouwer** [comment]
Heh. Looks like other tests are now failing 😅  I could take a look at this tomorrow.

File: packages/vm/lib/evm/opcodes/functions.ts [hunk 1]
```diff
@@ -747,6 +747,23 @@ export const handlers: Map<number, OpHandler> = new Map([
...
+        } else if (value.length === 0 && found.length) {
+          runState.eei.useGas(
+            new BN(adjustSstoreGasEIP2929(runState, keyBuf, sstoreResetCost, 'reset'))
+          )
+          runState.eei.refundGas(new BN(runState._common.param('gasPrices', 'sstoreRefund')))
+        } else if (value.length !== 0 && !found.length) {
+          runState.eei.useGas(new BN(runState._common.param('gasPrices', 'sstoreSet')))
+        }
+      }
       await runState.eei.storageStore(keyBuf, value)
```
Comment (cgewecke) [inline packages/vm/lib/evm/opcodes/functions.ts:767]: Ah yes this make sense, sorry and thanks! 🙂 

Perhaps this misplaced stuff could also go in a function in `opcodes/utils` as `updateSStoreGas`?
```js
      updateSstoreGas(runState, found, setLengthLeftStorage(value))
      updateSstoreGasEIP1283(runState, found, setLengthLeftStorage(value))
      updateSstoreGasEIP2200(runState, found, setLengthLeftStorage(value), keyBuf)
```

and be gated by 
```js
// Before constantinople
if (!runState._common.gteHardfork('constantinople')){
  ... 
}
```

Comment (jochem-brouwer) [reply packages/vm/lib/evm/opcodes/functions.ts:767]: Yep great suggestion! I will also move the HF logic inside the SSTORE, because otherwise it seems that it updates SSTORE gas 3 times (which is not the case)

Comment (cgewecke) [reply packages/vm/lib/evm/opcodes/functions.ts:758]: Oh nice, yes that's a lot clearer now 💯

File: packages/vm/lib/evm/opcodes/EIP1283.ts [hunk 2]
```diff
@@ -9,51 +9,49 @@ import { RunState } from './../interpreter'
...
 export function updateSstoreGasEIP1283(runState: RunState, found: any, value: Buffer) {
-  if (runState._common.hardfork() === 'constantinople') {
-    const original = found.original
-    const current = found.current
-    if (current.equals(value)) {
-      // If current value equals new value (this is a no-op), 200 gas is deducted.
-      runState.eei.useGas(new BN(runState._common.param('gasPrices', 'netSstoreNoopGas')))
-      return
+  const original = found.original
+  const current = found.current
```
Comment (ryanio) [inline packages/vm/lib/evm/opcodes/EIP1283.ts:13]: personal style nit ^_^
```suggestion
  const { original, current } = found
```

File: packages/vm/lib/evm/opcodes/EIP2200.ts [hunk 3]
```diff
@@ -12,82 +12,66 @@ import { trap } from './util'
...
-    const original = found.original
-    const current = found.current
-    // Fail if not enough gas is left
-    if (
-      runState.eei.getGasLeft().lten(runState._common.param('gasPrices', 'sstoreSentryGasEIP2200'))
-    ) {
-      trap(ERROR.OUT_OF_GAS)
-    }
+  const original = found.original
+  const current = found.current
```
Comment (ryanio) [inline packages/vm/lib/evm/opcodes/EIP2200.ts:16]: personal style nit ^_^
```suggestion
  const { original, current } = found
```

**Comment by ryanio** [comment]
Great PR :) It looks like all the uses of `adjustSstoreGasEIP2929` are being wrapped in a `new BN`, should we just alter the function to return a BN and simplify some of the syntax?

**Comment by jochem-brouwer** [comment]
Can you point to these lines @ryanio ?

These `new BN` things are very misleading, I never understood why this was done in the first place as especially the `new` keyword implies that you are actually creating a `new` (i.e. independent) object.

However...

```
> a = new BN(1)
<BN: 1>
> b = new BN(a)
<BN: 1>
> b.iaddn(1)
<BN: 2>
> a
<BN: 2>
> b
<BN: 2>
```

**Comment by ryanio** [comment]
> These new BN things are very misleading, I never understood why this was done in the first place as especially the new keyword implies that you are actually creating a new (i.e. independent) object.

Yeah I find that confusing as well, that `clone()` is actually needed to create a new independent object. I would also expect it to be part of the `new BN` initialization.

re: `adjustSstoreGasEIP2929`, just look at all its uses here in the PR, it's returning a number but always needing to be wrapped as a BN, so my suggestion is to make the return value a BN so we can reduce some of these crazy amount of `new BN`s.

Most of it is `common.param` though, which we can possibly take in another PR, as you suggest in #914, would be pretty great to have that return a BN I think that would possibly reduce 100s of extra `new BN`s. I guess just being nit picky here, no stopper 😆

**Comment by jochem-brouwer** [comment]
Ah I see! Just a note here these `new BNs` are not introduced here, might look like it due to the diff but it is merely copying the original logic around. 

I think it would be great to do this in a seperate PR, possibly together with #914

**Comment by ryanio** [comment]
ah right ok, yeah sounds like something good for future work then. This LGTM then!

**Review by ryanio — APPROVED** [review]

**Comment by holgerd77** [comment]
@jochem-brouwer Great stuff here! 😄 

Could you please update this post-merge with a proper title and a short description on what was broken respectively has been fixed for the release notes? Thanks!

**Comment by holgerd77** [comment]
(also can please everyone try hard to internalize our new process of upgrading the release notes along PRs 😜  and then hopefully directly add to the release notes on PRs and also mention missing release notes on PR reviews? Seems this is still forgotten 80%+ of the times 😋  🎃 )
