### PR TITLE
API Tests for the bloom module

### LINKED ISSUE #333: Bloom.multiCheck() not working (double type conversion)
``Bloom.multiCheck()`` pre-converts string values provided to ``Buffer`` values, which is not working within the current implementation context (see also [this](https://github.com/ethereumjs/ethereumjs-vm/issues/332) issue pointing out inconsistent string/buffer type usage for the Bloom implementation).

For the current implementation to work the Buffer check/conversion has to be removed.

### PR DESCRIPTION
**Pull request by s1na**
This is the first sub-PR of #315, and contains only the tests added for `bloom`. I've cherry-picked commits from the other branch. Please let me know if you'd rather have it done some other way.

One case which is meant to test bloom's multiCheck fails. `multiCheck` converts inputs via hex to buffer, although `check` itself doesn't do such a thing.

This PR also fixes #333

### CODE REVIEW

File: tests/api/bloom.js [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+const utils = require('ethereumjs-util')
+
+const byteSize = 256
+
+tape('bloom', (t) => {
+  t.test('should initialize without params', (st) => {
+    const b = new Bloom()
+    st.deepEqual(b.bitvector, utils.zeros(byteSize), 'should be empty')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: Looks good.

File: tests/api/bloom.js [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('shouldnt initialize with invalid bitvector', (st) => {
+    st.throws(() => new Bloom('invalid'), /AssertionError/, 'should fail for invalid type')
+    st.throws(() => new Bloom(utils.zeros(byteSize / 2), /AssertionError/), 'should fail for invalid length')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: Nice, looks good.

File: tests/api/bloom.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('should contain values of hardcoded bitvector', (st) => {
+    const hex = '00000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000'
+    const vector = Buffer.from(hex, 'hex')
+
+    const b = new Bloom(vector)
+    st.true(b.check('value 1'), 'should contain value 1')
+    st.true(b.check('value 2'), 'should contain value 2')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: I actually am no bloom filter expert myself, could you explain - just for my understanding - where this 'value ' part of 'value 1' can be re-found in the hex string?

File: tests/api/bloom.js [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('check shouldnt be tautology', (st) => {
+    const b = new Bloom()
+    st.false(b.check('random value'), 'should not contain random value')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: This is already high-level criticism, don't necessarily needs to be updated, but the explanatory strings are bit misleading on first read, would be more clear with something like ``'should not contain string "random value"'``, a bit similar for other test messages.

Again, change or keep as you like - just as a note and maybe a bit picky. 😄

Otherwise: OK.

File: tests/api/bloom.js [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('should correctly add value', (st) => {
+    const b = new Bloom()
+    b.add('value')
+    let found = b.check('value')
+    st.true(found, 'should contain added value')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: OK.

File: tests/api/bloom.js [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('should check multiple values', (st) => {
+    const b = new Bloom()
+    b.add('value 1')
+    b.add('value 2')
+    let found = b.multiCheck(['value 1', 'value 2'])
+    st.true(found, 'should contain both values')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: Phew, the whole usage of types (string vs Buffer) in the Bloom implementation respectively the corresponding documentation is really a mess: but right, this is exactly what the tests you have written are for to discover! 😄 I've opened an according issue https://github.com/ethereumjs/ethereumjs-vm/issues/332.

Within the current implementation the Buffer conversion in the ``Bloom.multiCheck()`` method has to be removed, opened the following issue on this: https://github.com/ethereumjs/ethereumjs-vm/issues/333

Re-architecturing whole parts of the library definitely doesn't have to be part of the scope of the work you are doing here, it's already great that we've discovered this now.

If you want you can just comment out this test, then we can re-add once the issue from above is fixed. I would then approve this part of your PR series.

File: tests/api/bloom.js [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+  t.test('should or two filters', (st) => {
+    const b1 = new Bloom()
+    b1.add('value 1')
+    const b2 = new Bloom()
+    b2.add('value 2')
+
+    b1.or(b2)
+    st.true(b1.check('value 2'), 'should contain value 2 after or')
+    st.end()
+  })
```
Comment (holgerd77) [inline tests/api/bloom.js]: OK.

File: tests/api/bloom.js [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+
+  t.test('should generate the correct bloom filter value ', (st) => {
```
Comment (holgerd77) [inline tests/api/bloom.js]: Can you remove the blank space after 'value ' on this occasion?

File: tests/api/bloom.js [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+    let bloom = new Bloom()
+    bloom.add(Buffer.from('1d7022f5b17d2f8b695918fb48fa1089c9f85401', 'hex'))
+    bloom.add(Buffer.from('8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925', 'hex'))
+    bloom.add(Buffer.from('0000000000000000000000005409ed021d9299bf6814279a6a1411a7e866a631', 'hex'))
+    bloom.add(Buffer.from('0000000000000000000000001dc4c1cefef38a777b15aa20260a54e584b16c48', 'hex'))
+    st.equal(
+      bloom.bitvector.toString('hex'),
+      '00000000000000000000080000800000000000000000000000000000000000000000000000000000000000000000000000000000000004000000080000200000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000010008000000000000000002000000000000000000000000008000000000000'
+    )
+    st.end()
```
Comment (holgerd77) [inline tests/api/bloom.js]: OK.

**Comment by holgerd77** [comment]
TBH I've no idea what's wrong with this ``coveralls`` command, since this is working on other current PRs. Maybe it's because the PR is coming from a forked repository? That's the only thing I can think of.

File: tests/api/bloom.js (hunk 3 above)
Comment (s1na) [reply tests/api/bloom.js]: Back then I also looked at a helpful [tutorial](https://llimllib.github.io/bloomfilter-tutorial/) to learn their details, which mentions "To add an element to the Bloom filter, we simply hash it a few times and set the bits in the bit vector at the index of those hashes to 1."
