### PR TITLE
[VM] fix blockchain tests and add Homestead support

### LINKED ISSUE #813: Fix older HF blockchain tests test runner / test on older HFs
Currently the blockchain test runner is not working on older HF settings, e.g. on using the following `Byzantium` test command: `node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Byzantium`

The tests read are mixed up on the HF side (might be an issue on either `ethereumjs-testing` or `vm` side and tests are therefore failing.

This should be fixed. As a follow-up blockchain tests should be at least manually run once (or/and - maybe separate PR) integrated into nightly CI.

It is likely that not all tests will pass due to all the HF related changes lately. It would be good if this can be tackled before another HF implementation is started.

//cc @jochem-brouwer

### LINKED ISSUE #824: Intermediate state trie root in pre-Byzantium blocks during transactions
[EIP 658](https://eips.ethereum.org/EIPS/eip-658) which was introduced in Byzantium changes the transaction receipt. It swaps the intermediate transaction root (the state root after the transaction has executed) with the transaction execution status.

This poses problems for our current implementation of the VM, which is [mentioned in the code](https://github.com/ethereumjs/ethereumjs-vm/blob/071fdd9a37ef24c999fc096ba387c9f1e6326c21/packages/vm/lib/runBlock.ts#L255). 

The problem is that in `runBlock` we `checkpoint` the `StateManager` and then either `commit` or `revert` it, depending on if the VM had any internal errors (at least this seems to be the reason to me).

A naive fix (but also an ugly one) would do above only if we are at a fork >= Byzantium and thus checkpoint/commit every TX in order to get the state root. The problem with this is, that if the VM itself crashes, we are left with an unprocessed blocks and have no means to recover the previous state.

It seems to me that for < Byzantium VMs we need to add a similar checkpointing mechanism which is invoked every time we run a block. But I'm a bit in the dark here. Any ideas?

### PR DESCRIPTION
**Pull request by jochem-brouwer**
Closes #813. Closes #824.

Note: I have put more forks in the PR CI file.

### CODE REVIEW

**Comment by jochem-brouwer** [comment]
Right this is bad.

TangerineWhistle tests are not passing at all. Byzantium+ seems to locally pass (haven't ran all tests though but it seems like those forks work).

**Comment by jochem-brouwer** [comment]
If I generate the state root and put that state root in the receipt then the tests pass for Spurious Dragon and for Tangerine Whistle 1 test fails.

We thus need a way to keep the checkpoint/revert/commit functionality of `StateManager`, but we also need to be able to generate the state root if we have not yet committed this. I can think of a rather dirty way to do this; we add a method to `getStateRootTemp` to `StateManager` which flushes the cache to the trie, but keeps the original values in memory. It thus temporarily commits the state to the trie, gets the state root and then reverts all changes. This is essentially a checkpointing mechanism on top of the checkpointing mechanism, it is dirty, but it will do the job. Thoughts?

File: packages/vm/tests/BlockchainTestsRunner.js [hunk 1]
```diff
@@ -8,6 +8,12 @@ const level = require('level')
 const levelMem = require('level-mem')
 
 module.exports = async function runBlockchainTest(options, testData, t) {
+  // ensure that the test data is the right fork data
+  if (testData.network != options.forkConfigTestSuite) {
+    t.comment("skipping test: no data available for " + options.forkConfigTestSuite)
+    return
+  }
+
```
Comment (holgerd77) [inline packages/vm/tests/BlockchainTestsRunner.js:16]: This is too late in the process, false forks should be already filtered out when the test files are read (currently the code logic in `ethereumjs-util`) and there should be no output on this, this is otherwise causing too much unnecessary noise.

Will do a follow-up comment here: https://github.com/ethereumjs/ethereumjs-vm/pull/808

Comment (jochem-brouwer) [reply packages/vm/tests/BlockchainTestsRunner.js:16]: I see where you are getting from, but this is not the case for [state tests](https://github.com/ethereumjs/ethereumjs-vm/blob/071fdd9a37ef24c999fc096ba387c9f1e6326c21/packages/vm/tests/GeneralStateTestsRunner.js#L8) either: files are read and are then filtered out (this is thus not done in the `ethereumjs-testing` module, but actually in the state test runner which we define in the VM package).

So this is inconsistent. Do you think we should move this check to `ethereumjs-testing`? (Such that the runner *never* skips any tests?). I see in #808 you have moved all the testing logic in the VM package and I think this is a good idea; we can then move these fork checks to a more 'natural' place (i.e. the tests filter) and then let the runner only do anything if it actually has the right data to test.

**Comment by jochem-brouwer** [comment]
Will push some commits soon which has #814 merged on top of it. 

This changes `getStateRoot()` of `StateManager` to `getStateManager(force: boolean)`, where `force` is a parameter which forces the cache to be flushed even if there are uncommited checkpoints. This is necessary to get the intermediate state roots pre-Byzantium. This has the side-effect that if there is an internal VM error which rolls back the block, the state trie (MPT) now has values in them which should not be there (as they do not seem to be rolled back if the cache is reverted). This might be an undesirable side-effect.

**Comment by jochem-brouwer** [comment]
```
npm run build && npm run test:blockchain -- --fork=TangerineWhistle
```

```
1..2568
# tests 2568
# pass  2568
```

**Comment by jochem-brouwer** [comment]
Homestead:

```
1..6471
# tests 6471
# pass  6471
```

This does need the ethereumjs/ethereumjs-util#269 package though, otherwise randomStatetest94 fails. Will push asap.

File: packages/vm/lib/evm/opFns.ts [hunk 2]
```diff
@@ -676,16 +679,23 @@ export const handlers: { [k: string]: OpHandler } = {
...
+      // We are before Spurious Dragon and the account does not exist.
       // Call new account gas: account does not exist (it is not in the state trie, not even as an "empty" account)
-      const accountDoesNotExist = !(await runState.stateManager.accountExists(toAddressBuf))
-      if (accountDoesNotExist) {
-        runState.eei.useGas(new BN(runState._common.param('gasPrices', 'callNewAccount')))
-      }
+      runState.eei.useGas(new BN(runState._common.param('gasPrices', 'callNewAccount')))
+    }
+
+    gasLimit = maxCallGas(
```
Comment (jochem-brouwer) [inline packages/vm/lib/evm/opFns.ts:691]: Note that `maxCallGas` is called after we have deducted all the call gas (this was not done before, `callNewAccount` could be deducted after `maxCallGas`). This was a difference from geth, so this might actually fix some consensus issues if we would do a mainnet sync (although it is very strange that no state test has found this!). The issue is thus that the forwarded gas between geth/EthereumJS might be different.

**Comment by jochem-brouwer** [comment]
Blockchain tests, local:

```
Homestead
1..4370
# tests 4370
# pass  4370

TangerineWhistle
1..2562
# tests 2562
# pass  2562

SpuriousDragon
1..2577
# tests 2577
# pass  2577

Byzantium
1..9958
# tests 9958
# pass  9958

Constantinople
1..21554
# tests 21554
# pass  21554

Petersburg
1..21544
# tests 21544
# pass  21544

Istanbul
1..23665
# tests 23665
# pass  23665

MuirGlacier
1..23665
# tests 23665
# pass  23665
```

**Comment by holgerd77** [comment]
What is missing on this on this PR? Can this be updated easily? Would have some time for a review later during the evening.

**Comment by jochem-brouwer** [comment]
@holgerd77 will update!

**Comment by jochem-brouwer** [comment]
@holgerd77 I spent more time on this than I want to admit 😅  But it works! Note that in the tests all forks supported forks are added as state test; Homestead is also checked in the blockchain test.

The tests are still a bit ugly (but they do work now for older forks). I could make them a bit more prettier but I think that should be done in a new PR.

@evertonfraga could you specifically review the CI? 😄

File: packages/vm/lib/evm/memory.ts [hunk 3]
```diff
@@ -54,12 +54,18 @@ export default class Memory {
...
+    const loaded = Buffer.from(this._store.slice(offset, offset + size))
+    returnBuffer.fill(loaded, 0, loaded.length)
+
+    if (loaded.length < size) {
+      // fill the remaining part of the Buffer with zeros
+      returnBuffer.fill(0, loaded.length, size)
     }
-    return Buffer.from(loaded)
+
+    return returnBuffer
```
Comment (holgerd77) [inline packages/vm/lib/evm/memory.ts:68]: Just for my understanding, since I've read through both code versions a couple of times now and would assume that both would work: what has been changed/fixed here?

File: packages/vm/lib/state/stateManager.ts [hunk 4]
```diff
@@ -363,10 +363,11 @@ export default class DefaultStateManager implements StateManager {
...
+   * @param force - If set to `true`, force a cache flush even if there are uncommited checkpoints (this is set to `true` pre-Byzantium in order to get intermediate state roots for the receipts)
    * @returns {Promise<Buffer>} - Returns the state-root of the `StateManager`
    */
-  async getStateRoot(): Promise<Buffer> {
-    if (this._checkpointCount !== 0) {
+  async getStateRoot(force: boolean = false): Promise<Buffer> {
+    if (!force && this._checkpointCount !== 0) {
       throw new Error('Cannot get state root with uncommitted checkpoints')
     }
     await this._cache.flush()
```
Comment (holgerd77) [inline packages/vm/lib/state/stateManager.ts:373]: Ok, looks good.

File: packages/vm/lib/state/interface.ts [hunk 5]
```diff
@@ -22,7 +22,7 @@ export interface StateManager {
   checkpoint(): Promise<void>
   commit(): Promise<void>
   revert(): Promise<void>
-  getStateRoot(): Promise<Buffer>
+  getStateRoot(force: boolean): Promise<Buffer>
```
Comment (holgerd77) [inline packages/vm/lib/state/interface.ts:25]: Correct me if I am wrong, but I think `force` should be marked as `optional` in the interface, since there is a default value in the implementation.

File: packages/vm/package.json [hunk 6]
```diff
@@ -14,13 +14,14 @@
...
     "test:state:slow": "npm run test:state -- --runSkipped=slow",
     "test:buildIntegrity": "npm run test:state -- --test='stackOverflow'",
     "test:blockchain": "node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain",
-    "test:API": "tape -r ts-node/register --stack-size=1500 './tests/api/**/*.js'",
-    "test:API:browser": "karma start karma.conf.js",
+    "test:blockchain:allForks": "node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Homestead && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=TangerineWhistle && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=SpuriousDragon && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Byzantium && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Constantinople && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Petersburg && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=Istanbul && node -r ts-node/register --stack-size=1500 ./tests/tester --blockchain --fork=MuirGlacier",
```
Comment (holgerd77) [inline packages/vm/package.json:22]: Wonder if this can be simplified with something build upon something like `echo {'Istanbul','Byzantium'} | xargs -n1 | xargs -I v1 echo v1`, see [this](https://unix.stackexchange.com/questions/387076/passing-multiple-parameters-via-xargs) StackExchange question for some inspiration.

File: packages/vm/package.json [hunk 7]
```diff
@@ -14,13 +14,14 @@
     "coverage:test": "tape './tests/api/**/*.js' ./tests/tester.js --state --dist",
     "docs:build": "typedoc --options typedoc.js",
     "test:state": "ts-node ./tests/tester --state",
-    "test:state:allForks": "npm run test:state -- --fork=TangerineWhistle && npm run test:state -- --fork=SpuriousDragon && npm run test:state -- --fork=Byzantium && npm run test:state -- --fork=Constantinople && npm run test:state -- --fork=Petersburg && npm run test:state -- --fork=Istanbul && npm run test:state -- --fork=MuirGlacier",
-    "test:state:selectedForks": "npm run test:state -- --fork=Petersburg && npm run test:state -- --fork=TangerineWhistle",
+    "test:state:allForks": "npm run test:state -- --fork=Homestead && npm run test:state -- --fork=TangerineWhistle && npm run test:state -- --fork=SpuriousDragon && npm run test:state -- --fork=Byzantium && npm run test:state -- --fork=Constantinople && npm run test:state -- --fork=Petersburg && npm run test:state -- --fork=Istanbul && npm run test:state -- --fork=MuirGlacier",
```
Comment (holgerd77) [inline packages/vm/package.json:17]: Similar suggestion as for `blockchain:allForks`

File: packages/vm/tests/BlockchainTestsRunner.js (hunk 1 above)
Comment (holgerd77) [reply packages/vm/tests/BlockchainTestsRunner.js:16]: Ok, will see this as resolved for now.

File: packages/vm/lib/evm/opFns.ts [hunk 8]
```diff
@@ -893,9 +922,24 @@ function jumpIsValid(runState: RunState, dest: number): boolean {
...
+
+/**
+ * Returns an overflow-safe slice of an array. It right-pads
+ * the data with zeros to `length`.
+ * @param {BN} gasLimit - requested gas Limit
+ * @param {BN} gasLeft - current gas left
+ * @param {boolean} isTangerineWhistleOrLater - set to true if we are on TW or later (this converts this to the identify function if it is false)
+ */
+function maxCallGas(gasLimit: BN, gasLeft: BN, isTangerineWhistleOrLater: boolean): BN {
+  if (isTangerineWhistleOrLater) {
```
Comment (holgerd77) [inline packages/vm/lib/evm/opFns.ts:937]: Why not use the `Common` instance here directly?

File: packages/vm/lib/state/interface.ts (hunk 5 above)
Comment (jochem-brouwer) [reply packages/vm/lib/state/interface.ts:25]: I can try this, I tried using a default value in the interface (`false`) but TypeScript does not support this. Marking it optional in the interface sounds like a good idea, I think that might work, but I don't know if TypeScript supports these optional values in the interface. Will try.

File: packages/vm/lib/evm/memory.ts (hunk 3 above)
Comment (jochem-brouwer) [reply packages/vm/lib/evm/memory.ts:68]: There is a KECCAK test in the Homestead suite which requires one to hash ~1.5GB of data (`randomStateTest94`). The old approach uses too much memory (I assume because of how JS-arrays are implemented; one keeps pushing values into this array, thus expanding it). It runs out of memory on my pc (not sure if it also runs OOM on the CI) which has 16GB of RAM (also tested it with bumping the amount of RAM node can access). 

The issue is thus not that this changes any functionality; this however uses less memory as the new approach does not go OOM on my pc.

File: packages/vm/lib/evm/opFns.ts (hunk 8 above)
Comment (jochem-brouwer) [reply packages/vm/lib/evm/opFns.ts:937]: This makes more sense. Will update.

File: packages/vm/lib/evm/memory.ts (hunk 3 above)
Comment (holgerd77) [reply packages/vm/lib/evm/memory.ts:68]: Ah, nice explanation, thanks!

(and also cool "digging-deep")

**Comment by jochem-brouwer** [comment]
Looks like the rebase introduced an error.

**Comment by jochem-brouwer** [comment]
Okay, this should be fixed now (Ethash had an unhandled rejection in a Promise).

Ready for re-review @holgerd77

**Comment by holgerd77** [comment]
@jochem-brouwer ah, great, will start in 10 min. 😛

File: packages/vm/lib/evm/opFns.ts (hunk 8 above)
Comment (holgerd77) [reply packages/vm/lib/evm/opFns.ts:922]: Won't make this a blocker, but this constant is really a bit unnecessary. 😄

File: packages/vm/package.json [hunk 9]
```diff
@@ -14,13 +14,14 @@
     "coverage:test": "tape './tests/api/**/*.js' ./tests/tester.js --state --dist",
     "docs:build": "typedoc --options typedoc.js",
     "test:state": "ts-node ./tests/tester --state",
-    "test:state:allForks": "npm run test:state -- --fork=TangerineWhistle && npm run test:state -- --fork=SpuriousDragon && npm run test:state -- --fork=Byzantium && npm run test:state -- --fork=Constantinople && npm run test:state -- --fork=Petersburg && npm run test:state -- --fork=Istanbul && npm run test:state -- --fork=MuirGlacier",
-    "test:state:selectedForks": "npm run test:state -- --fork=Petersburg && npm run test:state -- --fork=TangerineWhistle",
+    "test:state:allForks": "echo {'Homestead','TangerineWhistle','SpuriousDragon','Byzantium','Constantinople','Petersburg','Istanbul','MuirGlacier'} | xargs -n1 | xargs -I v1 npm run test:state -- --fork=v1",
+    "test:state:selectedForks": "echo {'Homestead','TangerineWhistle','SpuriousDragon','Petersburg',} | xargs -n1 | xargs -I v1 npm run test:state -- --fork=v1",
```
Comment (holgerd77) [inline packages/vm/package.json:18]: 👍

File: packages/vm/lib/evm/opFns.ts [hunk 10]
```diff
@@ -713,7 +718,11 @@ export const handlers: { [k: string]: OpHandler } = {
     if (!value.isZero()) {
       runState.eei.useGas(new BN(runState._common.param('gasPrices', 'callValueTransfer')))
     }
-    gasLimit = maxCallGas(gasLimit, runState.eei.getGasLeft())
+    gasLimit = maxCallGas(gasLimit, runState.eei.getGasLeft(), runState)
+    // note that TW or later this cannot happen (it could have ran out of gas prior to getting here though)
```
Comment (holgerd77) [inline packages/vm/lib/evm/opFns.ts:722]: Won't make this a blocker either, but such abbreviations like `TW` are suboptimal since hard to read (I didn't make it at all to "Tangerine Whistle" on first round), better to fully write stuff like this down.

Comment (jochem-brouwer) [reply packages/vm/lib/evm/opFns.ts:722]: Good point, will keep it in mind 👍
